modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "${mod_issues}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoBlur = false
authors = "${mod_authors}"
description = '''
${mod_description}
'''
logoFile = "assets/frightsdelight/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_min_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.4,)"
ordering = "NONE"
side = "BOTH"